name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '2022'

      - name: Restore dependencies
        run: nuget restore creacion_de_empleados.sln

      - name: Build project
        run: |
          msbuild creacion_de_empleados.sln /p:Configuration=Release

      - name: Run tests
        run: |
          cd TestFundionalidades
          dotnet test TestFundionalidades.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'TestFundionalidades/test-results.trx'
