name: CI/CD_Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2
        
      - name: Restore dependencies
        run: nuget restore creacion_de_empleados.sln

      - name: Build the project
        run: dotnet build creacion_de_empleados.sln --configuration Release

      - name: Run tests
        run: |
          cd TestFundionalidades
          dotnet test TestFundionalidades.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'creacion_de_empleados/TestResults/test-results.trx'

