name: CI/CD_Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          architecture: x64

      - name: Restore dependencies
        run: cd creacion_de_empleados && dotnet restore

      - name: Build the project
        run: dotnet build creacion_de_empleados.sln --configuration Release --no-restore -p:Platform=x64

      - name: Create TestResults Directory (if it doesn't exist)
        run: mkdir -p creacion_de_empleados/TestResults

      - name: Run tests
        run: cd creacion_de_empleados && dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'creacion_de_empleados/TestResults/*.trx'
