name: CI/CD_Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
          
      - name: Set environment variable to x64
        run: |
          set DOTNET_CLI_TELEMETRY_OPTOUT=1
          set DOTNET_ROOT=C:\Program Files\dotnet
          set PATH=%PATH%;%DOTNET_ROOT%
          set MSBuildArchitecture=x64

      - name: Restore dependencies
        run: cd creacion_de_empleados && dotnet restore

      - name: Build the project
        run: cd creacion_de_empleados && dotnet build --configuration Release --no-restore

      - name: Run tests
        run: cd creacion_de_empleados && dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: 'creacion_de_empleados/TestResults/test-results.trx'
